version: 1
disable_existing_loggers: False

formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    fmt: "%(levelprefix)s | %(asctime)s | %(name)s | %(message)s"
    use_colors: true
  access:
    "()": uvicorn.logging.AccessFormatter
    fmt: '%(levelprefix)s | %(asctime)s | %(client_addr)s - "%(request_line)s" %(status_code)s'

filters:
  rename_uvicorn_error:
    "()": app.configs.log_filters.RenameLoggerFilter  # Python 코드에서 정의한 Filter 클래스 경로

handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    filters: [rename_uvicorn_error]
    stream: ext://sys.stdout
  access:
    class: logging.StreamHandler
    formatter: access
    stream: ext://sys.stdout

loggers:
  uvicorn.error:
    level: INFO
    handlers: [default]
    propagate: False
  uvicorn.access:
    level: INFO
    handlers: [access]
    propagate: False

root:
  level: INFO
  handlers: [default]